# Generated by Django 5.0.6 on 2024-07-29 10:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gasstation_remove_profile_mobile_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_permit',
            field=models.FileField(upload_to='permits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imges', models.FileField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])])),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gasstation')),
            ],
        ),
    ]
