# Generated by Django 5.0.6 on 2024-07-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_gasstation_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstation',
            name='gasoline_type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
