# Generated by Django 5.0.6 on 2024-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_gasstation_gasoline_type_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepromo',
            name='discount',
            field=models.TextField(),
        ),
    ]
