# Generated by Django 5.0.6 on 2024-08-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_activepromo_expired_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activepromo',
            old_name='discount',
            new_name='description',
        ),
        migrations.AddField(
            model_name='activepromo',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
